/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package radiobuttondemo;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class PetSelector extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PetSelector.class.getName());

    /**
     * Creates new form PetSelector
     */
    public PetSelector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbBird = new javax.swing.JRadioButton();
        rbCat = new javax.swing.JRadioButton();
        rbDog = new javax.swing.JRadioButton();
        rbRabbit = new javax.swing.JRadioButton();
        rbPig = new javax.swing.JRadioButton();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rbBird);
        rbBird.setText("Bird");
        rbBird.addActionListener(this::rbBirdActionPerformed);

        buttonGroup1.add(rbCat);
        rbCat.setText("Cat");
        rbCat.setToolTipText("");
        rbCat.setActionCommand("Cat");
        rbCat.addActionListener(this::rbCatActionPerformed);

        buttonGroup1.add(rbDog);
        rbDog.setText("Dog");
        rbDog.addActionListener(this::rbDogActionPerformed);

        buttonGroup1.add(rbRabbit);
        rbRabbit.setText("Rabbit");
        rbRabbit.addActionListener(this::rbRabbitActionPerformed);

        buttonGroup1.add(rbPig);
        rbPig.setText("Pig");
        rbPig.addActionListener(this::rbPigActionPerformed);

        lblImage.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPig)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbBird, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rbCat, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rbDog, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rbRabbit, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rbBird)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbCat)
                        .addGap(12, 12, 12)
                        .addComponent(rbDog)
                        .addGap(62, 62, 62)
                        .addComponent(rbRabbit))
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPig)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbBirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBirdActionPerformed
        showPet("bird.jpg", "Bird"); 
    }//GEN-LAST:event_rbBirdActionPerformed

    private void rbCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCatActionPerformed
        showPet("cat.jpg", "Cat");
    }//GEN-LAST:event_rbCatActionPerformed

    private void rbDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDogActionPerformed
        showPet("dog.jpg", "Dog");
    }//GEN-LAST:event_rbDogActionPerformed

    private void rbRabbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRabbitActionPerformed
         showPet("rabbit.jpg", "Rabbit");
    }//GEN-LAST:event_rbRabbitActionPerformed

    private void rbPigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPigActionPerformed
        showPet("pig.jpg", "Pig");
    }//GEN-LAST:event_rbPigActionPerformed

    private void showPet(String imageFile, String petName) {

    ImageIcon icon = new ImageIcon(getClass().getResource("/images/" + imageFile));

    lblImage.setIcon(icon);

    JOptionPane.showMessageDialog(this, "You selected: " + petName);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PetSelector().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JRadioButton rbBird;
    private javax.swing.JRadioButton rbCat;
    private javax.swing.JRadioButton rbDog;
    private javax.swing.JRadioButton rbPig;
    private javax.swing.JRadioButton rbRabbit;
    // End of variables declaration//GEN-END:variables
}
